/*
 * openapi-examples API
 * 
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * This class was auto generated by openapi-jaxrs-client (https://github.com/jskov/openapi-jaxrs-client).
 * Do not edit the class manually.
 */

package mada.tests.e2e.dto.primitives.dto;

import java.util.Objects;

/**
 * Primitives
 */
@javax.annotation.Generated(value = "dk.mada.jaxrs.generator.DtoGenerator")
public class Primitives   {
  private boolean aBoolean;

  private byte aByte;

  private short aShort;

  private int anInt;

  private long aLong;

  private String aString;

  public Primitives aBoolean(boolean aBoolean) {
    this.aBoolean = aBoolean;
    return this;
  }

  /**
   * Get aBoolean
   * @return aBoolean
   **/
  public boolean getABoolean() {
    return aBoolean;
  }

  public void setABoolean(boolean aBoolean) {
    this.aBoolean = aBoolean;
  }

  public Primitives aByte(byte aByte) {
    this.aByte = aByte;
    return this;
  }

  /**
   * Get aByte
   * @return aByte
   **/
  public byte getAByte() {
    return aByte;
  }

  public void setAByte(byte aByte) {
    this.aByte = aByte;
  }

  public Primitives aShort(short aShort) {
    this.aShort = aShort;
    return this;
  }

  /**
   * Get aShort
   * @return aShort
   **/
  public short getAShort() {
    return aShort;
  }

  public void setAShort(short aShort) {
    this.aShort = aShort;
  }

  public Primitives anInt(int anInt) {
    this.anInt = anInt;
    return this;
  }

  /**
   * Get anInt
   * @return anInt
   **/
  public int getAnInt() {
    return anInt;
  }

  public void setAnInt(int anInt) {
    this.anInt = anInt;
  }

  public Primitives aLong(long aLong) {
    this.aLong = aLong;
    return this;
  }

  /**
   * Get aLong
   * @return aLong
   **/
  public long getALong() {
    return aLong;
  }

  public void setALong(long aLong) {
    this.aLong = aLong;
  }

  public Primitives aString(String aString) {
    this.aString = aString;
    return this;
  }

  /**
   * Get aString
   * @return aString
   **/
  public String getAString() {
    return aString;
  }

  public void setAString(String aString) {
    this.aString = aString;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Primitives other = (Primitives) o;
    return Objects.equals(this.aBoolean, other.aBoolean) &&
        Objects.equals(this.aByte, other.aByte) &&
        Objects.equals(this.aShort, other.aShort) &&
        Objects.equals(this.anInt, other.anInt) &&
        Objects.equals(this.aLong, other.aLong) &&
        Objects.equals(this.aString, other.aString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aBoolean, aByte, aShort, anInt, aLong, aString);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Primitives {\n");
    
    sb.append("    aBoolean: ").append(toIndentedString(aBoolean)).append("\n");
    sb.append("    aByte: ").append(toIndentedString(aByte)).append("\n");
    sb.append("    aShort: ").append(toIndentedString(aShort)).append("\n");
    sb.append("    anInt: ").append(toIndentedString(anInt)).append("\n");
    sb.append("    aLong: ").append(toIndentedString(aLong)).append("\n");
    sb.append("    aString: ").append(toIndentedString(aString)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

