/*
 * openapi-examples API
 * 
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * This class was auto generated by openapi-jaxrs-client (https://github.com/jskov/openapi-jaxrs-client).
 * Do not edit the class manually.
 */

package mada.tests.e2e.dto.jackson.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * SerializerInfoDto
 */
@JsonPropertyOrder({
  SerializerInfoDto.JSON_PROPERTY_BETA,
  SerializerInfoDto.JSON_PROPERTY_ALPHA,
  SerializerInfoDto.JSON_PROPERTY_ZAP_RENAMED,
  SerializerInfoDto.JSON_PROPERTY_MUST_INCLUDE
})
@javax.annotation.Generated(value = "dk.mada.jaxrs.generator.DtoGenerator")
public class SerializerInfoDto   {
  public static final String JSON_PROPERTY_BETA = "beta";
  @JsonProperty(JSON_PROPERTY_BETA)
  private String beta;

  public static final String JSON_PROPERTY_ALPHA = "alpha";
  @JsonProperty(JSON_PROPERTY_ALPHA)
  private String alpha;

  public static final String JSON_PROPERTY_ZAP_RENAMED = "zapRenamed";
  @JsonProperty(JSON_PROPERTY_ZAP_RENAMED)
  private String zapRenamed;

  public static final String JSON_PROPERTY_MUST_INCLUDE = "mustInclude";
  @JsonProperty(JSON_PROPERTY_MUST_INCLUDE)
  private String mustInclude;

  public SerializerInfoDto beta(String beta) {
    this.beta = beta;
    return this;
  }

  /**
   * Get beta
   * @return beta
   **/
  public String getBeta() {
    return beta;
  }

  public void setBeta(String beta) {
    this.beta = beta;
  }

  public SerializerInfoDto alpha(String alpha) {
    this.alpha = alpha;
    return this;
  }

  /**
   * Get alpha
   * @return alpha
   **/
  public String getAlpha() {
    return alpha;
  }

  public void setAlpha(String alpha) {
    this.alpha = alpha;
  }

  public SerializerInfoDto zapRenamed(String zapRenamed) {
    this.zapRenamed = zapRenamed;
    return this;
  }

  /**
   * Get zapRenamed
   * @return zapRenamed
   **/
  public String getZapRenamed() {
    return zapRenamed;
  }

  public void setZapRenamed(String zapRenamed) {
    this.zapRenamed = zapRenamed;
  }

  public SerializerInfoDto mustInclude(String mustInclude) {
    this.mustInclude = mustInclude;
    return this;
  }

  /**
   * Get mustInclude
   * @return mustInclude
   **/
  @ApiModelProperty(required = true, value = "")
  public String getMustInclude() {
    return mustInclude;
  }

  public void setMustInclude(String mustInclude) {
    this.mustInclude = mustInclude;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SerializerInfoDto other = (SerializerInfoDto) o;
    return Objects.equals(this.beta, other.beta) &&
        Objects.equals(this.alpha, other.alpha) &&
        Objects.equals(this.zapRenamed, other.zapRenamed) &&
        Objects.equals(this.mustInclude, other.mustInclude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beta, alpha, zapRenamed, mustInclude);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SerializerInfoDto {\n");
    
    sb.append("    beta: ").append(toIndentedString(beta)).append("\n");
    sb.append("    alpha: ").append(toIndentedString(alpha)).append("\n");
    sb.append("    zapRenamed: ").append(toIndentedString(zapRenamed)).append("\n");
    sb.append("    mustInclude: ").append(toIndentedString(mustInclude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

