/*
 * Test
 * 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * This class was auto generated by openapi-jaxrs-client (https://github.com/jskov/openapi-jaxrs-client).
 * Do not edit the class manually.
 */

package mada.tests.e2e.opts.parser.unwrap.dto;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ArchivePDF
 */
public class ArchivePDF   {
  private List<String> stringList = new ArrayList<>();

  private byte[] byteList;

  public ArchivePDF stringList(List<String> stringList) {
    this.stringList = stringList;
    return this;
  }

  public ArchivePDF addStringListItem(String stringListItem) {
    if (this.stringList == null) {
      this.stringList = new ArrayList<>();
    }
    this.stringList.add(stringListItem);
    return this;
  }

  /**
   * Get stringList
   * @return stringList
   **/
  public List<String> getStringList() {
    return stringList;
  }

  public void setStringList(List<String> stringList) {
    this.stringList = stringList;
  }

  public ArchivePDF byteList(byte[] byteList) {
    this.byteList = byteList;
    return this;
  }

  /**
   * Get byteList
   * @return byteList
   **/
  public byte[] getByteList() {
    return byteList;
  }

  public void setByteList(byte[] byteList) {
    this.byteList = byteList;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArchivePDF other = (ArchivePDF) o;
    return Objects.equals(this.stringList, other.stringList) &&
        Objects.equals(this.byteList, other.byteList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stringList, byteList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArchivePDF {\n");
    
    sb.append("    stringList: ").append(toIndentedString(stringList)).append("\n");
    sb.append("    byteList: ").append(toIndentedString(byteList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

