/*
 * openapi-examples API
 * 
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * This class was auto generated by openapi-jaxrs-client (https://github.com/jskov/openapi-jaxrs-client).
 * Do not edit the class manually.
 */

package mada.tests.e2e.dto.arrays.dto;

import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * ArraysDto
 */
public class ArraysDto   {
  private boolean[] booleans;

  private byte[] bytes;

  private short[] shorts;

  private int[] ints;

  private long[] longs;

  private String[] strings;

  private Simple[] refs;

  public ArraysDto booleans(boolean[] booleans) {
    this.booleans = booleans;
    return this;
  }

  /**
   * Get booleans
   * @return booleans
   **/
  @ApiModelProperty(value = "")
  
  public boolean[] getBooleans() {
    return booleans;
  }

  public void setBooleans(boolean[] booleans) {
    this.booleans = booleans;
  }

  public ArraysDto bytes(byte[] bytes) {
    this.bytes = bytes;
    return this;
  }

  /**
   * Get bytes
   * @return bytes
   **/
  @ApiModelProperty(value = "")
  
  public byte[] getBytes() {
    return bytes;
  }

  public void setBytes(byte[] bytes) {
    this.bytes = bytes;
  }

  public ArraysDto shorts(short[] shorts) {
    this.shorts = shorts;
    return this;
  }

  /**
   * Get shorts
   * @return shorts
   **/
  @ApiModelProperty(value = "")
  
  public short[] getShorts() {
    return shorts;
  }

  public void setShorts(short[] shorts) {
    this.shorts = shorts;
  }

  public ArraysDto ints(int[] ints) {
    this.ints = ints;
    return this;
  }

  /**
   * Get ints
   * @return ints
   **/
  @ApiModelProperty(value = "")
  
  public int[] getInts() {
    return ints;
  }

  public void setInts(int[] ints) {
    this.ints = ints;
  }

  public ArraysDto longs(long[] longs) {
    this.longs = longs;
    return this;
  }

  /**
   * Get longs
   * @return longs
   **/
  @ApiModelProperty(value = "")
  
  public long[] getLongs() {
    return longs;
  }

  public void setLongs(long[] longs) {
    this.longs = longs;
  }

  public ArraysDto strings(String[] strings) {
    this.strings = strings;
    return this;
  }

  /**
   * Get strings
   * @return strings
   **/
  @ApiModelProperty(value = "")
  
  public String[] getStrings() {
    return strings;
  }

  public void setStrings(String[] strings) {
    this.strings = strings;
  }

  public ArraysDto refs(Simple[] refs) {
    this.refs = refs;
    return this;
  }

  /**
   * Get refs
   * @return refs
   **/
  @ApiModelProperty(value = "")
  
  public Simple[] getRefs() {
    return refs;
  }

  public void setRefs(Simple[] refs) {
    this.refs = refs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArraysDto other = (ArraysDto) o;
    return Objects.equals(this.booleans, other.booleans) &&
        Objects.equals(this.bytes, other.bytes) &&
        Objects.equals(this.shorts, other.shorts) &&
        Objects.equals(this.ints, other.ints) &&
        Objects.equals(this.longs, other.longs) &&
        Objects.equals(this.strings, other.strings) &&
        Objects.equals(this.refs, other.refs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(booleans, bytes, shorts, ints, longs, strings, refs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArraysDto {\n");
    
    sb.append("    booleans: ").append(toIndentedString(booleans)).append("\n");
    sb.append("    bytes: ").append(toIndentedString(bytes)).append("\n");
    sb.append("    shorts: ").append(toIndentedString(shorts)).append("\n");
    sb.append("    ints: ").append(toIndentedString(ints)).append("\n");
    sb.append("    longs: ").append(toIndentedString(longs)).append("\n");
    sb.append("    strings: ").append(toIndentedString(strings)).append("\n");
    sb.append("    refs: ").append(toIndentedString(refs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

