/*
 * openapi API Title
 * openapi API description
 *
 * The version of the OpenAPI document: openapi API Version
 * Contact: openapi API contact email
 */

package mada.tests.e2e.dto.oneof.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.Objects;
import javax.validation.Valid;

/**
 * AbstractType
 */
@JsonPropertyOrder({
  AbstractType.JSON_PROPERTY_VALUE_ENUM,
  AbstractType.JSON_PROPERTY_VALUE_INTEGER,
  AbstractType.JSON_PROPERTY_VALUE_STRING
})
@JsonIgnoreProperties(
  value = "implName", // ignore manually set implName, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the implName to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "implName", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = TypeBar.class, name = "BAR"),
  @JsonSubTypes.Type(value = TypeFoo.class, name = "FOO"),
})
@javax.annotation.processing.Generated(value = "dk.mada.jaxrs.Generator")
public class AbstractType {
  public static final String JSON_PROPERTY_VALUE_ENUM = "valueEnum";
  @JsonProperty(JSON_PROPERTY_VALUE_ENUM)
  private OtherEnum valueEnum;

  public static final String JSON_PROPERTY_VALUE_INTEGER = "valueInteger";
  @JsonProperty(JSON_PROPERTY_VALUE_INTEGER)
  private Integer valueInteger;

  public static final String JSON_PROPERTY_VALUE_STRING = "valueString";
  @JsonProperty(JSON_PROPERTY_VALUE_STRING)
  private String valueString;

  public AbstractType valueEnum(OtherEnum valueEnum) {
    this.valueEnum = valueEnum;
    return this;
  }

  /**
   * Get valueEnum
   * @return valueEnum
   **/
  @Valid
  public OtherEnum getValueEnum() {
    return valueEnum;
  }

  public void setValueEnum(OtherEnum valueEnum) {
    this.valueEnum = valueEnum;
  }

  public AbstractType valueInteger(Integer valueInteger) {
    this.valueInteger = valueInteger;
    return this;
  }

  /**
   * Get valueInteger
   * @return valueInteger
   **/
  public Integer getValueInteger() {
    return valueInteger;
  }

  public void setValueInteger(Integer valueInteger) {
    this.valueInteger = valueInteger;
  }

  public AbstractType valueString(String valueString) {
    this.valueString = valueString;
    return this;
  }

  /**
   * Get valueString
   * @return valueString
   **/
  public String getValueString() {
    return valueString;
  }

  public void setValueString(String valueString) {
    this.valueString = valueString;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof AbstractType)) {
      return false;
    }
    AbstractType other = (AbstractType) o;
    return Objects.equals(this.valueEnum, other.valueEnum) &&
        Objects.equals(this.valueInteger, other.valueInteger) &&
        Objects.equals(this.valueString, other.valueString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(valueEnum, valueInteger, valueString);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AbstractType {");
    sb.append("\n    valueEnum: ").append(toIndentedString(valueEnum));
    sb.append("\n    valueInteger: ").append(toIndentedString(valueInteger));
    sb.append("\n    valueString: ").append(toIndentedString(valueString));
    sb.append("\n}");
    return sb.toString();
  }

  private String toIndentedString(Object o) {
    return Objects.toString(o).replace("\n", "\n    ");
  }
}
