/*
 * openapi API Title
 * openapi API description
 *
 * The version of the OpenAPI document: openapi API Version
 * Contact: openapi API contact email
 */

package mada.tests.e2e.dto.oneof.dto;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonIgnoreProperties(
		  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
		  allowSetters = true // allows the type to be set during deserialization
		)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({
	@JsonSubTypes.Type(value = AnswerAndSubmitPurposeAndScopeTask.class, name = "ANSWER_AND_SUBMIT_PURPOSE_AND_SCOPE"),
	@JsonSubTypes.Type(value = AttachFileToDocumentTask.class, name = "ATTACH_FILE_TO_DOCUMENT"),
	@JsonSubTypes.Type(value = QualifyDocumentTask.class, name = "QUALIFY_DOCUMENT"),
	@JsonSubTypes.Type(value = QualifyOrClosePurposeAndScopeTask.class, name = "QUALIFY_OR_CLOSE_PURPOSE_AND_SCOPE"),
	@JsonSubTypes.Type(value = SignStatementOfTruthTask.class, name = "SIGN_STATEMENT_OF_TRUTH"),
	@JsonSubTypes.Type(value = TaxInfoTask.class, name = "TAX_INFO"),
})
@Schema(description = "Derived from various functionalities, a Customer Room contains a set of tasks used for guiding the bank and customer through necessary data collection.", anyOf = { AnswerAndSubmitPurposeAndScopeTask.class, AttachFileToDocumentTask.class, QualifyDocumentTask.class, QualifyOrClosePurposeAndScopeTask.class, SignStatementOfTruthTask.class, TaxInfoTask.class })
public interface Task {
}
