/*
 * KFA-KRO
 *
 * The version of the OpenAPI document: 1.1.1
 */

package mada.tests.e2e.dto.allof_composite.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.Objects;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/**
 * <b>NOTE: Discriminator mapping is not shown in Swagger UI (as of september 2023). Read the .yaml spec file directly
 * for the discriminator mapping or use an alternative UI, for example Redoc.</b> <br/><br/> The identification of the
 * contact. Can only be changed when identification.loginId is not set.
 */
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = SMSMailIdentification.class, name = "SMS_MAIL"),
  @JsonSubTypes.Type(value = VirkPersonIdentification.class, name = "VIRK_PERSON"),
})
@Schema(description = " <b>NOTE: Discriminator mapping is not shown in Swagger UI (as of september 2023). Read the .yaml spec file directly for the discriminator mapping or use an alternative UI, for example Redoc.</b> <br/><br/> The identification of the contact. Can only be changed when identification.loginId is not set. ")
@javax.annotation.processing.Generated(value = "dk.mada.jaxrs.Generator")
public abstract class Identification {
  public static final String JSON_PROPERTY_LOCKED = "locked";
  @JsonProperty(JSON_PROPERTY_LOCKED)
  @Schema(readOnly = true, description = "If identification is protected by a secret, this field is true.<br>When true the following operations can only be done when the known secret is supplied in header x-locked-secret.<ul><li>PATCH of contact with a different identification type than already set.</li></ul>")
  private Boolean locked;

  public static final String JSON_PROPERTY_LOGIN_ID = "loginId";
  @JsonProperty(JSON_PROPERTY_LOGIN_ID)
  @Schema(readOnly = true, description = "DA: Login id<br/>Login id, from the security token.")
  private String loginId;

  public static final String JSON_PROPERTY_TYPE = "type";
  @JsonProperty(JSON_PROPERTY_TYPE)
  @Schema(required = true)
  private IdentificationType type;

  public Identification locked(Boolean locked) {
    this.locked = locked;
    return this;
  }

  /**
   * If identification is protected by a secret, this field is true.<br>When true the following operations can only be
   * done when the known secret is supplied in header x-locked-secret.<ul><li>PATCH of contact with a different
   * identification type than already set.</li></ul>
   *
   * @return locked
   **/
  public Boolean isLocked() {
    return locked;
  }

  public void setLocked(Boolean locked) {
    this.locked = locked;
  }

  public Identification loginId(String loginId) {
    this.loginId = loginId;
    return this;
  }

  /**
   * DA: Login id<br/>Login id, from the security token.
   *
   * @return loginId
   **/
  public String getLoginId() {
    return loginId;
  }

  public void setLoginId(String loginId) {
    this.loginId = loginId;
  }

  public Identification type(IdentificationType type) {
    this.type = Objects.requireNonNull(type, "Property type is required, cannot be null");
    return this;
  }

  /**
   * Get type
   * @return type
   **/
  @NotNull @Valid
  public IdentificationType getType() {
    return type;
  }

  public void setType(IdentificationType type) {
    this.type = Objects.requireNonNull(type, "Property type is required, cannot be null");
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof Identification)) {
      return false;
    }
    Identification other = (Identification) o;
    return Objects.equals(this.locked, other.locked) &&
        Objects.equals(this.loginId, other.loginId) &&
        Objects.equals(this.type, other.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locked, loginId, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Identification {");
    sb.append("\n    locked: ").append(toIndentedString(locked));
    sb.append("\n    loginId: ").append(toIndentedString(loginId));
    sb.append("\n    type: ").append(toIndentedString(type));
    sb.append("\n}");
    return sb.toString();
  }

  private String toIndentedString(Object o) {
    return Objects.toString(o).replace("\n", "\n    ");
  }
}
