/*
 * openapi-examples API
 * 
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * This class was auto generated by openapi-jaxrs-client (https://github.com/jskov/openapi-jaxrs-client).
 * Do not edit the class manually.
 */

package mada.tests.e2e.opts.generator.bigdecimal_double.dto;

import java.math.BigDecimal;
import java.util.Objects;
import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Primitives
 */
@javax.annotation.Generated(value = "dk.mada.jaxrs.generator.DtoGenerator")
public class Primitives   {
  private Boolean aBoolean;

  private Byte aByte;

  private Short aShort;

  private Integer anInt;

  private Long aLong;

  private Float aFloat;

  private Double aDouble;

  private String aString;

  public Primitives aBoolean(Boolean aBoolean) {
    this.aBoolean = aBoolean;
    return this;
  }

  /**
   * Get aBoolean
   * @return aBoolean
   **/
  public Boolean isABoolean() {
    return aBoolean;
  }

  public void setABoolean(Boolean aBoolean) {
    this.aBoolean = aBoolean;
  }

  public Primitives aByte(Byte aByte) {
    this.aByte = aByte;
    return this;
  }

  /**
   * Get aByte
   * @return aByte
   **/
  public Byte getAByte() {
    return aByte;
  }

  public void setAByte(Byte aByte) {
    this.aByte = aByte;
  }

  public Primitives aShort(Short aShort) {
    this.aShort = aShort;
    return this;
  }

  /**
   * Get aShort
   * @return aShort
   **/
  public Short getAShort() {
    return aShort;
  }

  public void setAShort(Short aShort) {
    this.aShort = aShort;
  }

  public Primitives anInt(Integer anInt) {
    this.anInt = anInt;
    return this;
  }

  /**
   * Get anInt
   * @return anInt
   **/
  public Integer getAnInt() {
    return anInt;
  }

  public void setAnInt(Integer anInt) {
    this.anInt = anInt;
  }

  public Primitives aLong(Long aLong) {
    this.aLong = aLong;
    return this;
  }

  /**
   * Get aLong
   * @return aLong
   **/
  public Long getALong() {
    return aLong;
  }

  public void setALong(Long aLong) {
    this.aLong = aLong;
  }

  public Primitives aFloat(Float aFloat) {
    this.aFloat = aFloat;
    return this;
  }

  /**
   * Get aFloat
   * @return aFloat
   **/
  public Float getAFloat() {
    return aFloat;
  }

  public void setAFloat(Float aFloat) {
    this.aFloat = aFloat;
  }

  public Primitives aDouble(Double aDouble) {
    this.aDouble = aDouble;
    return this;
  }

  public Primitives aDouble(BigDecimal aDouble) {
    this.aDouble = aDouble == null ? null : aDouble.doubleValue();
    return this;
  }

  /**
   * Get aDouble
   * @return aDouble
   **/
  public Double getADoubleDouble() {
    return aDouble;
  }

  @JsonIgnore
  public BigDecimal getADouble() {
    return aDouble == null ? null : new BigDecimal(aDouble);
  }

  public void setADoubleDouble(Double aDouble) {
    this.aDouble = aDouble;
  }

  @JsonIgnore
  public void setADouble(BigDecimal aDouble) {
    this.aDouble = aDouble == null ? null : aDouble.doubleValue();
  }

  public Primitives aString(String aString) {
    this.aString = aString;
    return this;
  }

  /**
   * Get aString
   * @return aString
   **/
  public String getAString() {
    return aString;
  }

  public void setAString(String aString) {
    this.aString = aString;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Primitives other = (Primitives) o;
    return Objects.equals(this.aBoolean, other.aBoolean) &&
        Objects.equals(this.aByte, other.aByte) &&
        Objects.equals(this.aShort, other.aShort) &&
        Objects.equals(this.anInt, other.anInt) &&
        Objects.equals(this.aLong, other.aLong) &&
        Objects.equals(this.aFloat, other.aFloat) &&
        Objects.equals(this.aDouble, other.aDouble) &&
        Objects.equals(this.aString, other.aString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aBoolean, aByte, aShort, anInt, aLong, aFloat, aDouble, aString);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Primitives {");
    sb.append("\n    aBoolean: ").append(toIndentedString(aBoolean));
    sb.append("\n    aByte: ").append(toIndentedString(aByte));
    sb.append("\n    aShort: ").append(toIndentedString(aShort));
    sb.append("\n    anInt: ").append(toIndentedString(anInt));
    sb.append("\n    aLong: ").append(toIndentedString(aLong));
    sb.append("\n    aFloat: ").append(toIndentedString(aFloat));
    sb.append("\n    aDouble: ").append(toIndentedString(aDouble));
    sb.append("\n    aString: ").append(toIndentedString(aString));
    sb.append("\n}");
    return sb.toString();
  }

  private String toIndentedString(Object o) {
    return Objects.toString(o).replace("\n", "\n    ");
  }
}

