name: Snyk analysis
on:
  push:
    branches:
      - DISABLED-NO-GRADLE21-VARIANT-YET-main
      # See https://github.com/snyk/actions/pull/134
      # PR from Dec 2023, not accepted? Maybe ditch this...

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk21@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --all-sub-projects
