name: Snyk analysis
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk17@7fad562681122205233d1242c3bb39598c5393da
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
